[package]
name = "pdu_exporter"
authors = ["Erlangga Yudi Pradana"]
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = 3
codegen-units = 1

[dependencies]
axum = { version = "0.8.8", features = ["tokio"] }
base64 = "0.22.1"
bcrypt = "0.19.0"
blake3 = "1.8.5"
getrandom = "0.4.2"
log = "0.4.29"
log4rs = "1.4.0"
reqwest = "0.13.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.52.1", features = ["rt-multi-thread", "signal"] }
