[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = 3
codegen-units = 1

[package]
name = "pdu_exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["tokio"] }
base64 = "0.22.1"
bcrypt = "0.17.0"
serde_yaml = "0.9.34"
tokio = { version = "1.46.1", features = ["full"] }
